### ISSUE TITLE
Add tamil language to translate

### ISSUE THREAD

**Issue by vpguru** [groovelauncher/GrooveLauncherLocalization#13]
Please add tamil in crowdin or provide push access to upload translated json..

**Comment by cherryhoax** [comment]
I've added it

**Comment by vpguru** [comment]
Since, i don't have push acces to this project. I'm unable to upload translated files/folders to Language folder. 

Please create "ta" folder with "en" files. I'll translate then

**Comment by vpguru** [comment]
Translated TA in crowdin
